var SystemMenu;

$.ajax({
    type:'post',
    url:'/getMenu',
    async:false,
    success:function (a) {
        SystemMenu = eval(""+a+"");
    }


});


/*
var SystemMenu = [{
    title: '系统管理',
    icon: '&#xe646;',
    isCurrent: true,
    menu: [{
        title: '基础数据',
        icon: '&#xe620;',
        href: '',
        isCurrent: true,
        children: [{
            title: '首页',
            href: 'workbench.html',
            isCurrent: true
        }, {
            title: '收派标准',
            href: 'basicData/deliveryStandard.html',
            isCurrent: false
        }, {
            title: '基础档案',
            href: 'basicData/basicArchives.html',
            isCurrent: false
        }, {
            title: '班车设置',
            href: 'basicData/shuttleBusSet.html',
            isCurrent: false
        }, {
            title: '取派员设置',
            href: 'basicData/dispatchingPersonnelSet.html',
            isCurrent: false
        }, {
            title: '区域设置',
            href: 'basicData/areaSet.html',
            isCurrent: false
        }, {
            title: '管理分区',
            href: 'basicData/partition.html',
            isCurrent: false
        }, {
            title: '管理定区',
            href: 'basicData/zone.html',
            isCurrent: false
        }, {
            title: '收派时间管理',
            href: 'basicData/deliveryTime.html',
            isCurrent: false
        }, ]
    }, {
        title: '权限管理',
        icon: '&#xe62f;',
        href: '',
        isCurrent: false,
        children: [{
            title: '单位管理',
            href: 'systemManagement/sysUnit.html',
            isCurrent: false
        }, {
            title: '员工管理',
            href: 'systemManagement/sysEmp.html',
            isCurrent: false
        }, {
            title: '栏目管理',
            href: 'systemManagement/sysMenu.html',
            isCurrent: false
        }, {
            title: '角色管理',
            href: 'systemManagement/sysRole.html',
            isCurrent: false
        }, ]
    }, ]
}, {
    title: '取派',
    icon: '&#xe63f;',
    isCurrent: false,
    menu: [{
        title: '受理',
        icon: '&#xe62f;',
        href: 'null',
        isCurrent: true,
        children: [{
            title: '业务受理',
            href: 'acceptance/businessAcceptance.html',
            isCurrent: false
        }, {
            title: '工作单快速录入',
            href: 'acceptance/worksheetQuickInput.html',
            isCurrent: false
        }, {
            title: '工作单查询',
            href: 'acceptance/worksheetQuery.html',
            isCurrent: false
        }, ]
    }, {
        title: '调度',
        icon: '&#xe62f;',
        href: 'null',
        isCurrent: false,
        children: [{
            title: '查台转单',
            href: 'dispatch/checkTable.html',
            isCurrent: false
        }, {
            title: '人工调度',
            href: 'dispatch/manualScheduling.html',
            isCurrent: false
        }, {
            title: '签收录入',
            href: 'dispatch/signInput.html',
            isCurrent: false
        }, {
            title: '取消签收申请确认',
            href: 'dispatch/cancelSignApplicationConfirmation.html',
            isCurrent: false
        }, {
            title: '宣传任务',
            href: 'dispatch/propagandaTask.html',
            isCurrent: false
        }, ]
    }, {
        title: '返货',
        icon: '&#xe62f;',
        href: 'null',
        isCurrent: false,
        children: [{
            title: '返货申请',
            href: 'return/returnApply.html',
            isCurrent: false
        }, {
            title: '返货申请确认',
            href: 'return/returnApplyConfirm.html',
            isCurrent: false
        }, {
            title: '生成返货单',
            href: 'return/returnInvoiceProduce.html',
            isCurrent: false
        }, ]
    }, {
        title: '包装材料管理',
        icon: '&#xe647;',
        href: 'null',
        isCurrent: false,
        children: [{
            title: '包装材料物品管理',
            href: 'packagingMaterialManagement/packagingMaterialManagement.html',
            isCurrent: false
        }, {
            title: '入库管理',
            href: 'packagingMaterialManagement/warehousingManagement.html',
            isCurrent: false
        }, {
            title: '出库管理',
            href: 'packagingMaterialManagement/outboundManagement.html',
            isCurrent: false
        }, {
            title: '库存管理',
            href: 'packagingMaterialManagement/inventoryManagement.html',
            isCurrent: false
        }, ]
    }, {
        title: '包装',
        icon: '&#xe611;',
        href: 'null',
        isCurrent: false,
        children: [{
            title: '包装信息录入',
            href: 'packing/packagingInformationInput.html',
            isCurrent: false
        }, {
            title: '包装信息查询',
            href: 'packing/packagingInformationQuery.html',
            isCurrent: false
        }, ]
    }, {
        title: '大物流管理',
        icon: '&#xe62f;',
        href: '',
        isCurrent: false,
        children: [{
            title: '大物流发货对照表',
            href: 'largeLogisticsManagement/invoiceComparisonTable.html',
            isCurrent: false
        }, ]
    }, ]
}, {
    title: '中转',
    icon: '&#xe646;',
    isCurrent: false,
    menu: [{
        title: '分拣管理',
        icon: '&#xe62f;',
        href: 'null',
        isCurrent: true,
        children: [{
            title: '入库',
            href: 'sortingManagement/storage.html',
            isCurrent: false
        }, {
            title: '出库',
            href: 'sortingManagement/theLibrary.html',
            isCurrent: false
        }, {
            title: '盘库',
            href: 'sortingManagement/check.html',
            isCurrent: false
        }, {
            title: '合包',
            href: 'sortingManagement/package.html',
            isCurrent: false
        }, {
            title: '拆包',
            href: 'sortingManagement/unpacking.html',
            isCurrent: false
        }, {
            title: '出入库查询',
            href: 'sortingManagement/outOfStorageQuery.html',
            isCurrent: false
        }, {
            title: '库存查询',
            href: 'sortingManagement/stockQuery.html',
            isCurrent: false
        }, {
            title: '合包查询',
            href: 'sortingManagement/packageQuery.html',
            isCurrent: false
        }, {
            title: '单货异常监控',
            href: 'sortingManagement/singleCargoExceptionMonitoring.html',
            isCurrent: false
        }, ]
    }, {
        title: '进出港管理',
        icon: '&#xe62f;',
        href: 'null',
        isCurrent: false,
        children: [{
            title: '出港配载',
            href: 'portEntryManagement/departureStowage.html',
            isCurrent: false
        }, {
            title: '提货管理',
            href: 'portEntryManagement/deliveryManagement.html',
            isCurrent: false
        }, {
            title: '进港分单',
            href: 'portEntryManagement/entryOrder.html',
            isCurrent: false
        }, {
            title: '出港配载查询',
            href: 'portEntryManagement/departureStowageQuery.html',
            isCurrent: false
        }, {
            title: '到达时间录入',
            href: 'portEntryManagement/arrivalTimeInput.html',
            isCurrent: false
        }, ]
    }, {
        title: '物流管理',
        icon: '&#xe62f;',
        href: 'null',
        isCurrent: false,
        children: [{
            title: '跟踪表登记',
            href: 'physicalDistributionManagement/traceTableRegister.html',
            isCurrent: false
        }, {
            title: '跟踪表查询',
            href: 'physicalDistributionManagement/traceTableQuery.html',
            isCurrent: false
        }, {
            title: '物流交接单查询',
            href: 'physicalDistributionManagement/logisticsQuery.html',
            isCurrent: false
        }, {
            title: '时间统计',
            href: 'physicalDistributionManagement/timeStatistics.html',
            isCurrent: false
        }, {
            title: '货量统计',
            href: 'physicalDistributionManagement/volumeStatistics.html',
            isCurrent: false
        }, ]
    }, ]
}, ]
*/
